-- examinprigressboot/releases/version/1.0/db/0001_create_tables_rollback.sql

BEGIN WORK;

DROP Sequence examinprigress_sequence;

-- =====================

DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS address_type CASCADE;
DROP TABLE IF EXISTS contact_query CASCADE;
DROP TABLE IF EXISTS mailing_list CASCADE;
DROP TABLE IF EXISTS forgotten_password CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS result CASCADE;
DROP TABLE IF EXISTS result_type CASCADE;
DROP TABLE IF EXISTS answer CASCADE;
DROP TABLE IF EXISTS answer_type CASCADE;
DROP TABLE IF EXISTS question_status CASCADE;
DROP TABLE IF EXISTS question CASCADE;
DROP TABLE IF EXISTS question_type CASCADE;
DROP TABLE IF EXISTS section_status CASCADE;
DROP TABLE IF EXISTS section CASCADE;
DROP TABLE IF EXISTS exam_token CASCADE;
DROP TABLE IF EXISTS invite CASCADE;
DROP TABLE IF EXISTS exam_status CASCADE;
DROP TABLE IF EXISTS token_consumed CASCADE;
DROP TABLE IF EXISTS exam CASCADE;
DROP TABLE IF EXISTS exam_timer_type CASCADE;
DROP TABLE IF EXISTS payment_history CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS teacher CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS domain_organisation CASCADE;
DROP TABLE IF EXISTS "role" CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS answer_students CASCADE;

-- =====================

COMMIT;
